server:
  port: ${PORT}

spring:
  output:
    ansi:
      enabled: ALWAYS
  cache:
    redis:
      time-to-live: 600000
  redis:
    host: ${REDIS_URL}
    password: ${REDIS_PASS}
    port: ${REDIS_PORT}

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver